{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beeshoes-be-ingress
  namespace: {{ include "beeshoes-app.namespace" . }}
  labels:
    {{- include "beeshoes-app.backend.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.backend.ingress.className }}
  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - path: {{ .Values.backend.ingress.path }}
            pathType: {{ .Values.backend.ingress.pathType }}
            backend:
              service:
                name: {{ include "beeshoes-app.backend.serviceName" . }}
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
